import "@/styles/globals.css"
import "@/styles/fonts.css"

export const metadata = {
  title: "TCB Concursos | Apostilas Digitais",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return(
    <html lang="pt">
      <head>
        <link rel="preload" href="/globals.css" as="style"/>
        <link rel="preload" href="/fonts/Inter.ttf" as="font" type="font/ttf" crossOrigin="anonymous"/>
        <link rel="stylesheet" href="/globals.css"/>
      </head>

      <body>
        {children}
      </body>
    </html>
  );
}